Feature/fifth milestone
widzthedvloper/calculator-react pull request #4
Opened 2021-08-09 20:15 UTC by widzthedvloper

This branch contains:
-     Update logic files
-     Make sure buttons is displayed correctly on the page
-     Deploy the app to Heroku
-     Style the calculator just like it looks in the Microverse photo.

2021-08-09 20:54 UTC, rukundoeric requested changes
Hi @widzthedvloper , 

_Great job so far 👏 💯 👍. However, there are few issues we need to address before we move on. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯
  - Codebase looks clean and professional. 💯 

## Required Changes ♻️
  - [ ] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
  - N/A

Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-08-09 20:54 UTC, rukundoeric commented on src/components/Button.js
> +/* eslint-disable react/prop-types */
- [ ] <b>REQUIRED:</b> You overused `eslint-disable`. it's like making changes in Eslint config. they represent style guidelines that you share with your team - which is a group of all Microverse students. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/) and [Zendesk](https://microverse.zendesk.com/hc/en-us/articles/1500002085202-February-2nd-2021-linter-errors-as-a-reason-of-project-invalidation-)). kindy try to fix the errors instead of ignoring them.

2021-08-09 20:54 UTC, rukundoeric commented on src/components/ButtonPanel.js
> +/* eslint-disable react/prop-types */
- [ ] <b>REQUIRED:</b> You overused `eslint-disable`. it's like making changes in Eslint config. they represent style guidelines that you share with your team - which is a group of all Microverse students. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/) and [Zendesk](https://microverse.zendesk.com/hc/en-us/articles/1500002085202-February-2nd-2021-linter-errors-as-a-reason-of-project-invalidation-)). kindy try to fix the errors instead of ignoring them.

2021-08-09 20:54 UTC, rukundoeric commented on src/logic/calculate.js
> +    // eslint-disable-next-line max-len
- [ ] <b>REQUIRED:</b> You overused `eslint-disable`. it's like making changes in Eslint config. they represent style guidelines that you share with your team - which is a group of all Microverse students. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/) and [Zendesk](https://microverse.zendesk.com/hc/en-us/articles/1500002085202-February-2nd-2021-linter-errors-as-a-reason-of-project-invalidation-)). kindy try to fix the errors instead of ignoring them.

2021-08-09 20:54 UTC, rukundoeric commented on src/logic/calculate.js
>  }
- [ ] <b>REQUIRED:</b> `Calculate` function is not functioning exactly as expected. it seems like It can't accept numbers with more than 1 digit before clicking on the operator. This is not correct because calculators are supposed to be able to calculate any kind of number in simple basic operations. Check out this [video](https://www.loom.com/share/a3664448685e4fa0887d29d06c2ffe5f) if you want to understand what is happening.

2021-08-10 20:49 UTC, bellom approved these changes
## Hi @widzthedvloper :clap: 

**Great work making all the necessary corrections from the previous review.**

# Status: Approved 👍 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next milestone :slightly_smiling_face:_ 

**Best**

2021-08-10 20:49 UTC, bellom commented on src/logic/calculate.js
> +
### Heads-up
Division by zero is not handled properly yet. Let's fix this.
The reason is that when a division by zero happens, we should return an error message like `division error`

Divide a number by zero (e.g. 4 / 0)

2021-08-10 20:49 UTC, merged